#!/usr/bin/env python3

import os
import csv
import json
import sys

def main():
    bsf_input_file = os.path.join(sys.path[0],
        'bsf2finn-unit-test-data-BSF.csv')
    with open(bsf_input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    bsf_fires = [{k: d[k] for k in d} for d in data]

    finn_input_file = os.path.join(sys.path[0],
        'bsf2finn-unit-test-data-FINN.csv')
    with open(finn_input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    finn_fires = [{k: d[k] for k in d} for d in data]

    output_file = os.path.abspath(os.path.join(sys.path[0],
        '../../test/unit/blueskyutils/bsf2wrfchem/bsf2finndata.py'))
    with open(output_file, 'w') as f:
        f.write("BSF_FIRES = " + json.dumps(bsf_fires, indent=4))
        f.write("\n")
        f.write("FINN_FIRES = " + json.dumps(finn_fires, indent=4))

if __name__ == '__main__':
    main()
