#!/usr/bin/env python3

import os
import csv
import json
import sys

def main():
    input_file = os.path.join(sys.path[0], 'fccs2genveg.csv')
    with open(input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    data = {e['FCCS_Code']: e['GENVEG'] for e in data}

    output_file = os.path.abspath(os.path.join(sys.path[0],
        '../../blueskyutils/bsf2wrfchem/fccs2genveg.py'))
    with open(output_file, 'w') as f:
        f.write("FCCS2GENVEG = " + json.dumps(data, indent=4))

if __name__ == '__main__':
    main()
