#!/usr/bin/env python3

import os
import csv
import json
import sys

def main():
    input_file = os.path.join(sys.path[0],
        'bsf2finn-species-conversion-factors.csv')
    with open(input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    data = {e.pop('finn_veg_id'): e for e in data}

    output_file = os.path.abspath(os.path.join(sys.path[0],
        '../../blueskyutils/bsf2wrfchem/speciation.py'))
    with open(output_file, 'w') as f:
        f.write("BSF2FINN_SPECIATION_FACTORS = "
            + json.dumps(data, indent=4))

if __name__ == '__main__':
    main()
