#!/usr/bin/env python3

import os
import csv
import json
import sys

NUM_FIRES = 1
DATE = "20130817"

def main():
    bsf_input_file = os.path.join(sys.path[0],
        'fire_locations_{}.csv'.format(DATE))
    with open(bsf_input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    bsf_fires = [{k: d[k] for k in d} for d in data][:NUM_FIRES]

    finn_input_file = os.path.join(sys.path[0],
        '{}_SF2-BSF2FINN.csv'.format(DATE))
    with open(finn_input_file, 'r') as f:
        data = [r for r in csv.DictReader(f)]
    finn_fires = [{k: d[k] for k in d} for d in data][:NUM_FIRES]
    for f in finn_fires:
        f.pop('DAY')
        f.pop('TIME')
        for k in f:
            if k != 'GENVEG':
                f[k] = float(f[k])

    output_file = os.path.abspath(os.path.join(sys.path[0],
        '../../unit/blueskyutils/bsf2wrfchem/bsf2finndata.py'))
    with open(output_file, 'w') as f:
        f.write("BSF_FIRES = " + json.dumps(bsf_fires, indent=4))
        f.write("\n")
        f.write("FINN_FIRES = " + json.dumps(finn_fires, indent=4))

if __name__ == '__main__':
    main()
